### ISSUE TITLE
Anisotropic GRNN converges to all sigmas equal NaN

### ISSUE THREAD

**Issue by Drewniacki** [federhub/pyGRNN#2]
I am attempting to use Anisotropic GRNN to correlate data, where input (X) has only 544 lines (data points), but potentially over 300 dimensions. Seems like the model every so often converges to all sigmas equal NaN. I could not find any correlation, but clearly it get's more frequent with the growing number of input dimension.

See the attached CSV file with a summary of my findings. "X_tran shape" shows the tada it was trained on, it is always a random subset of a higher dimension array.
[modeling results.zip](https://github.com/federhub/pyGRNN/files/5934712/modeling.results.zip)

Would you be able to advise on possible reason of that? Is it a possible error in the module?
I initiate the model by `GRNN(calibration="gradient_search")`

**Comment by Drewniacki** [comment]
Upon closer inspection I found out that NaNs were returned by `optimization` function nested in `calibrate_sigma` method. If `scipy.optimize.minimize(***)['sucess'] == False` then model returns all sigmas equal NaN. 

In my case `scipy.optimize.minimize` was returning message 
>  TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT'

despite of providing quite accurate sigmas. They were then overriden by `optimization` function to array of NaNs. 

Changing initiation to `GRNN(method='Powell')` worked in my case but may be a good idea for fit method to raise a warning instead returning NaN sigmas in future updates of the package.

**Comment by federhub** [comment]
Thanks. I added a warning in the optimization function. I think another possible solution, instead of changing the `scipy.optimize.minimize` method, could be increasing the number of  `n_restarts_optimizer`
