### ISSUE TITLE
Initializing GRNN with default parameters will raise ValueError

### ISSUE THREAD

**Issue by Drewniacki** [federhub/pyGRNN#3]
Initializing GRNN with default parameters `model = GRNN()` will raise ValueError if scikit-learn version 0.24 or higher is used. That is caused by `KFold(n_splits= self.n_splits, random_state=self.seed)` call on line 161. Since ver. 0.24 it is an incorrect way to call KFold class with int value passed to `random_state` but without changing `shuffle=True`. It can be either `KFold(n_splits= self.n_splits, random_state=self.seed, shuffle=True)` or `KFold(n_splits= self.n_splits, random_state=None, shuffle=False)`.

Temporary way around this issue may be to intialize your model as `model = GRNN(seed=None)`

**Comment by federhub** [comment]
Thanks a lot for pointing this out. I updated the package to include` KFold(n_splits= self.n_splits, random_state=self.seed, shuffle=True)`
